version: '3.8'

services:
  load-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - etl-data-volume:/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    restart: "no"  # Run once and exit

volumes:
  etl-data-volume:
    name: etl-data-volume
