services:
  idx-extract:
    build: .
    container_name: idx-extract
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/
      - MONGO_DATABASE=idx_lapkeu
      - CHROMEDRIVER_EXECUTABLE_PATH=/usr/local/bin/chromedriver
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    network_mode: "bridge"
