version: '3.8'

services:
  load-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - shared-data:/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: "no"  # Run once and exit

volumes:
  shared-data:
    external: true
    name: transform_shared-data
