services:
  yfinance-transform:
    build: .
    container_name: yfinance-transform
    environment:
      - MONGO_HOST=host.docker.internal  # For connecting to MongoDB on host machine
      - MONGO_PORT=27017
      - SPARK_MASTER=local[*]
    volumes:
      - shared-data:/data  # Mount shared volume for JSON data
    restart: "no"  # Don't restart automatically as this is a one-time job
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  shared-data:
