version: '3.8'

services:
  idx-extract:
    build: .
    container_name: idx-extract
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/
      - MONGO_DATABASE=idx_lapkeu
      - CHROMEDRIVER_EXECUTABLE_PATH=/usr/local/bin/chromedriver
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - idx-network

  mongodb:
    image: mongo:5.0
    container_name: idx-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - idx-network

volumes:
  mongodb_data:

networks:
  idx-network:
    driver: bridge
